/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // Background colors for KPI cards
    'bg-blue-100',
    'bg-purple-100', 
    'bg-cyan-100',
    'bg-red-100',
    'bg-green-100',
    'bg-yellow-100',
    'bg-orange-100',
    // Text colors for KPI cards
    'text-blue-600',
    'text-purple-600',
    'text-cyan-600', 
    'text-red-600',
    'text-green-600',
    'text-yellow-600',
    'text-orange-600',
    // Gradient backgrounds for report difficulty levels
    'from-red-500',
    'via-pink-500', 
    'to-red-600',
    'from-orange-400',
    'via-yellow-500',
    'to-orange-600',
    'from-green-400',
    'via-emerald-500',
    'to-green-600',
    // Additional gradient combinations used in the component
    'from-purple-900',
    'via-blue-900',
    'to-blue-800',
    'from-blue-50',
    'via-white',
    'to-blue-100',
    'from-purple-100',
    'to-blue-100',
    'from-blue-100',
    'to-cyan-100',
    'from-purple-500',
    'to-blue-500',
    'from-purple-600',
    'to-blue-600',
    // Hover states
    'hover:from-purple-200',
    'hover:to-blue-200',
    'hover:from-blue-200',
    'hover:to-cyan-200',
    'hover:from-green-200',
    'hover:to-emerald-200',
    'hover:from-gray-200',
    'hover:to-slate-200',
    // Background opacity variants
    'bg-white/90',
    'bg-white/95',
    'bg-green-50/80',
    'bg-yellow-50/80',
    // Border colors
    'border-white/20',
    'border-green-500',
    'border-red-500',
    'border-yellow-500',
    'border-gray-300',
    'border-green-200',
    'border-yellow-400',
    'border-green-400',
    'border-blue-200',
    'border-purple-200'
  ]
}
